/**
 * Inline what the bundler used to inline.
 *
 * Two modules were built on `import.meta.glob(..., { eager: true })`: the page dictionaries, auto-discovered so a
 * workstream can add `src/i18n/pages/<theirs>.ts` and touch nothing shared, and the docs, read out of `docs/` as
 * raw markdown. That is a Vite feature. Next has no equivalent, and the alternative — hand-written import lists —
 * silently loses a file the day somebody adds one, which is exactly the failure the auto-discovery existed to
 * prevent (`docs-shell.test.ts` exists because a glob that matched nothing shipped an empty /docs).
 *
 * So the discovery moves here, to a generator that writes real modules, and `npm run gen:check` fails when they
 * are out of date. Same guarantee, no bundler magic, and the output is readable in a diff.
 */
import { readdirSync, readFileSync, writeFileSync, existsSync, statSync } from 'node:fs';
import { join, relative, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const check = process.argv.includes('--check');

const HEADER = '// GENERATED by scripts/gen-inline.mjs — do not edit. `npm run gen` rewrites it.\n';

/** Every file under `dir` matching `test`, depth-first, as paths relative to `dir`. */
function walk(dir, test, prefix = '') {
  if (!existsSync(dir)) return [];
  const out = [];
  for (const name of readdirSync(dir).sort()) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) out.push(...walk(full, test, `${prefix}${name}/`));
    else if (test(name)) out.push(`${prefix}${name}`);
  }
  return out;
}

// ── page dictionaries
const dictDir = join(root, 'src/i18n/pages');
const dictFiles = readdirSync(dictDir).filter((f) => f.endsWith('.ts') && f !== 'index.ts' && f !== 'generated.ts').sort();
const dicts = `${HEADER}
import type { Dict } from '../index';
${dictFiles.map((f, i) => `import * as m${i} from './${f.replace(/[.]ts$/, '')}';`).join('\n')}

/** Every dictionary module, in filename order. The index merges them. */
export const MODULES: Record<string, Dict>[] = [${dictFiles.map((_, i) => `m${i}`).join(', ')}] as unknown as Record<string, Dict>[];
`;

// ── docs markdown and their tables of contents
const docsDir = join(root, 'docs');
const mdFiles = walk(docsDir, (n) => n.endsWith('.md'));
const treeFiles = walk(docsDir, (n) => n === '_toctree.json');
const q = (s) => JSON.stringify(s);
const docs = `${HEADER}
/** Every markdown page under \`docs/\`, keyed by its path there. */
export const SOURCES: Record<string, string> = {
${mdFiles.map((f) => `  ${q(f)}: ${q(readFileSync(join(docsDir, f), 'utf8'))},`).join('\n')}
};

/** The tables of contents, keyed the same way. */
export const TREES: Record<string, unknown> = {
${treeFiles.map((f) => `  ${q(f)}: ${readFileSync(join(docsDir, f), 'utf8').trim()},`).join('\n')}
};
`;

let stale = 0;
for (const [path, content] of [
  [join(dictDir, 'generated.ts'), dicts],
  [join(root, 'src/screens/docs/generated.ts'), docs],
]) {
  const rel = relative(root, path);
  const current = existsSync(path) ? readFileSync(path, 'utf8') : null;
  if (current === content) { console.log(`same  ${rel}`); continue; }
  if (check) { console.error(`STALE ${rel}`); stale++; continue; }
  writeFileSync(path, content);
  console.log(`write ${rel}  (${content.length} bytes)`);
}
if (check && stale) {
  console.error(`\n${stale} generated file(s) out of date — run \`npm run gen\``);
  process.exit(1);
}
