// GENERATED by scripts/gen-inline.mjs — do not edit. `npm run gen` rewrites it.

import type { Dict } from '../index';
import * as m0 from './apps';
import * as m1 from './billing';
import * as m2 from './chat';
import * as m3 from './common';
import * as m4 from './detail';
import * as m5 from './docs';
import * as m6 from './hostedAgents';
import * as m7 from './lineage-check';
import * as m8 from './lineage';
import * as m9 from './linkedAgents';
import * as m10 from './me';
import * as m11 from './merge';
import * as m12 from './models';
import * as m13 from './operator';
import * as m14 from './organizations';
import * as m15 from './projects';
import * as m16 from './public';
import * as m17 from './retire';
import * as m18 from './sharedAgents';
import * as m19 from './table';
import * as m20 from './teach';
import * as m21 from './tracks';
import * as m22 from './verifier';

/** Every dictionary module, in filename order. The index merges them. */
export const MODULES: Record<string, Dict>[] = [m0, m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11, m12, m13, m14, m15, m16, m17, m18, m19, m20, m21, m22] as unknown as Record<string, Dict>[];
