// GENERATED by scripts/gen-inline.mjs — do not edit. `npm run gen` rewrites it.

import type { Dict } from '../index';
import * as m0 from './billing';
import * as m1 from './chat';
import * as m2 from './common';
import * as m3 from './detail';
import * as m4 from './docs';
import * as m5 from './hostedAgents';
import * as m6 from './lineage-check';
import * as m7 from './lineage';
import * as m8 from './me';
import * as m9 from './merge';
import * as m10 from './models';
import * as m11 from './operator';
import * as m12 from './public';
import * as m13 from './retire';
import * as m14 from './table';
import * as m15 from './teach';
import * as m16 from './tracks';
import * as m17 from './verifier';

/** Every dictionary module, in filename order. The index merges them. */
export const MODULES: Record<string, Dict>[] = [m0, m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11, m12, m13, m14, m15, m16, m17] as unknown as Record<string, Dict>[];
